---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #- name: Test building image.
      #  run: docker build -t docker-ansible .

      #- name: Run the built image.
      #  run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

      #- name: Verify Ansible is accessible in the built image.
      #  run: docker exec --tty test-container env TERM=xterm ansible --version
        
      - name: View context attributes
        uses: actions/github-script@v4
        with:
#           script: console.log(context.repo)
          script: console.log(context.push)
      
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
        
      - name: Create Issue
        if: failure()
        uses: buluma/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/bug_report.md
