---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout branch
        uses: actions/checkout@v2
        env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
      - name: log untrusted output
        run: |

          # disable command workflow processing
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

          # log untrusted output
          echo "untrusted output"

          # enable workflow command processing
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"


#       - name: Test building image.
#         run: docker build -t docker-ansible .

#       - name: Run the built image.
#         run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

#       - name: Verify Ansible is accessible in the built image.
#         run: docker exec --tty test-container env TERM=xterm ansible --version
        
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: console.log(context.payload.commits)
        
      - name: Create Issue
        if: failure()
        uses: buluma/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/bug_report.md
          body: Workflow failed for commit ${{github.sha}}
        
        id: create-issue
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
      
      # This will set the FOO environment variable within the
      # first `run` script, then instruct GitHub Actions to make
      # it available within subsequent `run` steps as well.
      - run: |
          export FOO=bar
          echo "::set-env name=FOO::$FOO"
      - run: echo $FOO
      
      - uses: nashmaniac/create-issue-action@v1.1
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}
